#!/bin/sh

# This script replaces environment variables in the runtime config file
# This is needed because frontend apps build environment variables at build time,
# but we want to be able to change them at runtime

# Create runtime environment config
cat > /var/www/html/runtime-config.js << EOF
// Runtime configuration - auto-generated by container
window.RUNTIME_CONFIG = {
  API_URL: "${REACT_APP_API_URL:-https://api.ucc-event-manager.com}",
  ENVIRONMENT: "${REACT_APP_ENVIRONMENT:-production}",
  BUILD_TIME: "${BUILD_TIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}",
  // Add other runtime configurations here
};
EOF

echo "Runtime config generated with API_URL=${REACT_APP_API_URL:-https://api.ucc-event-manager.com}" 