# The config.yml file contains the configuration of your NLU pipeline and policies.
# https://rasa.com/docs/rasa/model-configuration/

recipe: default.v1
language: hu

# Configuration for the NLU pipeline.
# https://rasa.com/docs/rasa/nlu/components/
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: rasa.nlu.llm.LLMEntityExtractor
  llm:
    model_group: ollama_deepseek # Reference the model group from endpoints.yml
  entity_examples:
    - entity: event_title
      examples: ["Hétvégi grillezés", "Nagybevásárlás", "Baráti sörözés"]
    - entity: event_description
      examples: ["Venni kell csevapot és krumplit.", "Lista: tej, kenyér, vaj.", "Találkozó a Fő téren."]
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.1

# Configuration for the policies.
# https://rasa.com/docs/rasa/policies/
policies:
- name: MemoizationPolicy
- name: RulePolicy
# - name: UnexpecTEDIntentPolicy
#   max_history: 5
#   epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
# - name: EnterpriseSearchPolicy
#   llm:
#     model_group: enterprise_search_generation
#   embeddings:
#     model_group: enterprise_search_embeddings
#   vector_store:
#     type: "faiss"
#     source: "/app/docs" # azért app mert a konténeren belül unix like filerendszer van és ott egyből app mappa van a rootban

assistant_id: 20250609-175652-coped-deed
